### PR TITLE
use a particular location to look for images for OpenLayers

### PR DESCRIPTION
**Pull request by drnextgis**
Picked from Leaflet viewer. Also fixed https://github.com/ckan/ckanext-geoview/issues/21 issue.

### CODE REVIEW

**Comment by drnextgis** [comment]
Hi, can anyone please review and merge if there no problems with it?

**Comment by drnextgis** [comment]
I've squashed commits into one and made PR rebase. Is it any chance this PR will be merged?

**Comment by amercader** [comment]
Sorry @drnextgis this slipped under my radar, too many open fronts.

Are you using this extension regularly? Would you like to help maintain it?

**Comment by drnextgis** [comment]
@amercader thanks! Yes we use this plugin extensively at @nextgis and of course would like to help maintain it. How we can help?

**Comment by amercader** [comment]
@drnextgis Basically we need help triaging issues and reviewing incoming PRs (as you might have noticed :) ). If you use the extension regularly it'd easier for you to keep on top of things. 
Just a comment on a PR saying if it looks good to you, if you've tested etc is fine, and after a while if you are up for it I can give you admin access to this repo so you can merge patches yourselves.

How does it sound?

**Comment by drnextgis** [comment]
Sounds good! I'll try to keep up with PRs and issues.

**Pull request merged**
